### ISSUE TITLE
When searching the search term cannot be canceled by pushing the x to the right of the search term.

### ISSUE THREAD

**Issue by CaptainKhan** [custodian/orn-warehouse#18]
i am using 2.0.4.14 fiskarsinjoki and when i search anything i have to basically use backspace to delete each letter:

search me
search m
search 
search
searc
sear
sea
se
s

instead of

search me X

---

**Comment by d9h02f** [comment]
You can also just select the whole text by long tapping on it, and then press backspace.

**Comment by CaptainKhan** [comment]
d9h02f its ok for one word say "search" but "search me" requires you to long press on search, then drag and.expand the selection field by holding and dragging it to the right over the me. Its quiet a pain.

**Comment by d9h02f** [comment]
Just hold it longer, it will select all text at once.

**Comment by CaptainKhan** [comment]
ok thanks that works
